// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/pillflow/AddScreen.tsx": () => import("../components/mockups/pillflow/AddScreen.tsx"),
  "./components/mockups/pillflow/StatsScreen.tsx": () => import("../components/mockups/pillflow/StatsScreen.tsx"),
  "./components/mockups/pillflow/TodayScreen.tsx": () => import("../components/mockups/pillflow/TodayScreen.tsx")
};
